name: Build Docker and test

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'
  workflow_dispatch:


jobs:  
  build-Docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Check env
        run: |
          echo "Check!"
          cat /etc/os-release
          ls -l
      - name: Build Docker image
        run: |
          docker build -t alpine_pwsh:latest .

      - name: Run container
        run: |
          docker run -d --name alpine_pwsh alpine_pwsh:latest
          # docker run --rm alpine_pwsh:latest pwsh -c "ls -l"
      - name: Run tests
        run: |
          docker exec alpine_pwsh pwsh -c 'ls -l && just -l && just test'
      - name: Create dev_build and run archiver
        run: |
          docker exec alpine_pwsh pwsh -c 'just createDevDir && just archive && tree'


