name: Test workflow

on:
  pull_request:
    branches: [main]
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'
  workflow_dispatch:


jobs:  
  run-tests:
    runs-on: ubuntu-latest
    container:
      image: demisto/powershell:7.4.6.117357
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Check env
        run: |
          echo "Check!"
          cat /etc/os-release
          ls -l
      - name: Install bash
        run: |
          sh
          apk update
          apk add bash
      - name: Install 7zip && just
        shell: bash
        run: |
          apk add 7zip just
      - name: Install Pester
        shell: pwsh
        run: |
          Install-Module Pester -Force
          Import-Module Pester -PassThru
      - name: Test script (Pester)
        run: |
          just -l
          just test
      - name: Create dev_build and run archiver
        run: |
          just createDevDir
          just archive
          tree

