name: Test workflow

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'
  workflow_dispatch:


jobs:  
  build-Docker:
    # needs: test-script
    runs-on: ubuntu-latest
    container:
      image: demisto/powershell:7.4.6.117357
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Check env
        run: |
          echo "Check!"
          cat /etc/os-release
          ls -l
      - name: Install bash
        run: |
          sh
          apk update
          apk add bash
      - name: Install dependencies
        run: |
          # 7zip
          apk update
          apk add 7zip

          # just
          apk add just

          # Pester
          exit
          Install-Module Pester -Force
          Import-Module Pester -PassThru
      - name: Check Pester installation
        shell: pwsh
        run: Import-Module Pester -PassThru
      - name: Test script (Pester)
        run: |
          just -l
          just test
      - name: Create dev_build and run archiver
        run: |
          just createDevDir
          just archive
          tree

