name: Test workflow

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'
  workflow_dispatch:


jobs:  
  build-Docker:
    # needs: test-script
    runs-on: ubuntu-latest
    container:
      image: demisto/powershell:7.4.6.117357
    steps:
      - name: Check
        run: |
          echo "Check!"
          cat /etc/os-release
      - name: Install bash
        run: |
          sh
          apk update
          apk add bash
      - name: Install dependencies
        run: |
          # 7zip
          apk update
          apk add 7zip

          # just
          apk add just

          # Pester
          exit
          Install-Module Pester -Force
          Import-Module Pester -PassThru

          Write-Output '>>> All dependencies installed'

