name: Test on Windows

on:
  pull_request:
    branches: [main]
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'
  workflow_dispatch:


jobs:  
  test-on-Windows:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Check env
        run: |
          echo "Check!"
          ls 
      - name: Install Chocolatey
        run: |
          Set-ExecutionPolicy Bypass -Scope Process -Force;
          [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072;
          iex ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))
      - name: Install 7zip
        run: |
          choco install 7zip -y
      - name: Install just
        run: |
          choco install just -y
      - name: Install Pester
        run: |
          Install-Module Pester -Force
          Import-Module Pester -PassThru
      - name: Test script (Pester)
        run: |
          just -l
          just test
          tree /F
      - name: Create dev_build and run archiver
        run: |
          just createDevDir
          just archive
          tree /F

      



